# RHELOSP-21987
- include: auth.yml
- hosts: control
  tasks:
  - name: check MDS service is started
    service:
      name: ceph-mds@{{ ansible_hostname }}
      state: started


  - name: check ceph conf for MDS section
    shell: grep -i mds /etc/ceph/ceph.conf


  - name: check MDS keyring is in place
    shell: ls /var/lib/ceph/mds/ceph-{{ ansible_hostname }}/
    become: true
