---
-
  - name: Get ceph health
    ceph_cmd: state=check
    become: True
    register: result
  - debug: var=result

  - name: Ceph is not healty
    command: echo "{{result.status.healt.overall_status}}" && exit 1
    when: "result.status.healt.overall_status != 'HEALTH_OK'"
