---
-
  - name: Get Ceph health
      ceph_cmd: state=check
      register: result
      become: yes

  - name: fail if not healthy
    command: exit 1
    when: "'HEALTH_OK' != result.status.health.overall.status"